# -*- coding: utf-8 -*-
"""Assignment2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1crajgqOQIeEEePJjK79W0zg2-pZUfFjJ
"""

number=int(input("Enter the number:"))
x=0
y=1
print(x,y,end=' ')
for i in range(1,number):
  x,y=y,x+y
  print(x,end=' ')

