# -*- coding: utf-8 -*-
"""Assignment-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_ipum_-X2Ka_25a8KJXcACxKakI3EBUC
"""

from math import pi
radius =1.1
area = pi*radius**2
print("the area of the circle is:",area)

filename=input("Enter the filename:")
name,extension=filename.split('.')
print("the extension of the file is:",extension)

