# -*- coding: utf-8 -*-
"""Assignment-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K1y3vgLGtV62uDIX3VBfFKQ7ZC5bjG6b
"""

a=int(input("enter the number:"))
list1=[]
for i in range(a):
  l=int(input("enter the element:"))
  list1.append(l)
print(list1)
for i in list1:
  if i>0:
    print(i,end=' ')

-4