# -*- coding: utf-8 -*-
"""Assignment-4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZIAU228tAc7HOUFIAJ_1ouFQfNZ5nwi-
"""

def most_frequent(n):
  d={}
  for i in n:
    if i not in d:
      d[i]=1
    else:d[i]+=1
  a=sorted(d.items(),key=lambda x:x[1],reverse=True)
  d=dict(a)
  return d
n=input("Enter the string:")
most_frequent(n)

